// ═══════════════════════════════════════════════════════════════
// OpenGravity — Mock LLM Provider
// Fully functional provider requiring ZERO API keys.
// Generates structured, deterministic responses for development.
// ═══════════════════════════════════════════════════════════════

import type {
  ModelProvider,
  ModelInfo,
  CompletionRequest,
  CompletionResponse,
  StreamChunk,
  ToolCall,
} from '../../types/index.js';

export class MockProvider implements ModelProvider {
  readonly name = 'mock';
  readonly models: ModelInfo[] = [
    {
      id: 'mock-default',
      provider: 'mock',
      name: 'Mock Default (Development)',
      contextWindow: 128_000,
      maxOutputTokens: 8_192,
      supportsTools: true,
      supportsStreaming: true,
      costPerInputToken: 0,
      costPerOutputToken: 0,
    },
  ];

  async isAvailable(): Promise<boolean> {
    return true; // Always available
  }

  async complete(request: CompletionRequest): Promise<CompletionResponse> {
    const start = Date.now();
    const lastUserMsg = [...request.messages].reverse().find(m => m.role === 'user');
    const userContent = lastUserMsg?.content ?? '';

    // If tools are provided, try to generate a tool call response
    if (request.tools && request.tools.length > 0) {
      const toolCall = this.generateToolCall(userContent, request.tools);
      if (toolCall) {
        return {
          id: `mock-${Date.now()}`,
          model: 'mock-default',
          content: '',
          toolCalls: [toolCall],
          usage: { promptTokens: this.estimateTokens(request.messages.map(m => m.content).join('')), completionTokens: 50, totalTokens: 0 },
          finishReason: 'tool_calls',
          latencyMs: Date.now() - start,
        };
      }
    }

    // Generate a structured text response
    const content = this.generateResponse(userContent, request.messages);

    const promptTokens = this.estimateTokens(request.messages.map(m => m.content).join(''));
    const completionTokens = this.estimateTokens(content);

    return {
      id: `mock-${Date.now()}`,
      model: 'mock-default',
      content,
      usage: {
        promptTokens,
        completionTokens,
        totalTokens: promptTokens + completionTokens,
      },
      finishReason: 'stop',
      latencyMs: Date.now() - start,
    };
  }

  async *stream(request: CompletionRequest): AsyncIterable<StreamChunk> {
    const response = await this.complete(request);
    const words = response.content.split(' ');
    const id = response.id;

    for (let i = 0; i < words.length; i++) {
      await new Promise(r => setTimeout(r, 20)); // Simulate latency
      yield {
        id,
        delta: (i > 0 ? ' ' : '') + words[i],
        done: i === words.length - 1,
      };
    }
  }

  // ── Private helpers ──

  private generateToolCall(userContent: string, tools: NonNullable<CompletionRequest['tools']>): ToolCall | null {
    const lower = userContent.toLowerCase();

    // Pattern-match user intent to available tools
    for (const tool of tools) {
      const toolName = tool.function.name;

      if ((lower.includes('read') || lower.includes('look') || lower.includes('show')) && toolName === 'read_file') {
        return {
          id: `call-${Date.now()}`,
          type: 'function',
          function: { name: 'read_file', arguments: JSON.stringify({ path: this.extractPath(lower) || './README.md' }) },
        };
      }

      if ((lower.includes('write') || lower.includes('create') || lower.includes('make')) && toolName === 'write_file') {
        return {
          id: `call-${Date.now()}`,
          type: 'function',
          function: {
            name: 'write_file',
            arguments: JSON.stringify({
              path: this.extractPath(lower) || './output.txt',
              content: '// Generated by OpenGravity Mock Provider\nconsole.log("Hello from OpenGravity!");\n',
            }),
          },
        };
      }

      if ((lower.includes('run') || lower.includes('execute') || lower.includes('command')) && toolName === 'run_command') {
        return {
          id: `call-${Date.now()}`,
          type: 'function',
          function: { name: 'run_command', arguments: JSON.stringify({ command: 'echo "OpenGravity Mock Execution"' }) },
        };
      }

      if ((lower.includes('search') || lower.includes('find') || lower.includes('grep')) && toolName === 'search_code') {
        return {
          id: `call-${Date.now()}`,
          type: 'function',
          function: { name: 'search_code', arguments: JSON.stringify({ query: lower.split(' ').slice(-2).join(' '), path: '.' }) },
        };
      }

      if ((lower.includes('verify') || lower.includes('prove') || lower.includes('check')) && toolName === 'z3_verify') {
        return {
          id: `call-${Date.now()}`,
          type: 'function',
          function: {
            name: 'z3_verify',
            arguments: JSON.stringify({
              constraints: [{ name: 'bounds_check', expression: 'x >= 0 && x < array_length', description: 'Array index in bounds' }],
              code: 'function getItem(arr, x) { return arr[x]; }',
            }),
          },
        };
      }

      if ((lower.includes('list') || lower.includes('dir') || lower.includes('ls')) && toolName === 'list_directory') {
        return {
          id: `call-${Date.now()}`,
          type: 'function',
          function: { name: 'list_directory', arguments: JSON.stringify({ path: '.' }) },
        };
      }
    }

    return null;
  }

  private generateResponse(userContent: string, messages: CompletionRequest['messages']): string {
    const lower = userContent.toLowerCase();

    // Check if this is a planning request
    if (lower.includes('plan') || lower.includes('break down') || lower.includes('steps')) {
      return JSON.stringify({
        taskDescription: userContent,
        reasoning: 'Analyzing the task and breaking it into logical steps based on dependencies.',
        estimatedComplexity: 'medium',
        steps: [
          { id: 1, description: 'Analyze requirements and understand the codebase structure', tool: 'list_directory', toolInput: { path: '.' }, dependsOn: [], status: 'pending' },
          { id: 2, description: 'Read existing relevant files for context', tool: 'read_file', toolInput: { path: './src/index.ts' }, dependsOn: [1], status: 'pending' },
          { id: 3, description: 'Generate the implementation code', tool: 'write_file', toolInput: { path: './src/output.ts', content: '// Implementation' }, dependsOn: [2], status: 'pending' },
          { id: 4, description: 'Verify the implementation with Z3 constraints', tool: 'z3_verify', toolInput: { constraints: [], code: '' }, dependsOn: [3], status: 'pending' },
          { id: 5, description: 'Run tests to validate correctness', tool: 'run_command', toolInput: { command: 'npm test' }, dependsOn: [4], status: 'pending' },
        ],
      }, null, 2);
    }

    // Check if asking for code generation
    if (lower.includes('code') || lower.includes('function') || lower.includes('implement') || lower.includes('write')) {
      return `Here's the implementation:

\`\`\`typescript
/**
 * Generated by OpenGravity Engine (Mock Provider)
 * Task: ${userContent}
 */

export function solution(input: unknown): unknown {
  // Validate input with Z3-inspired constraints
  if (input === null || input === undefined) {
    throw new Error('Input must not be null or undefined');
  }

  // Core logic placeholder
  const result = processInput(input);

  // Post-condition verification
  console.assert(result !== undefined, 'Result must be defined');
  return result;
}

function processInput(input: unknown): unknown {
  // Implementation based on the task requirements
  return input;
}
\`\`\`

This implementation includes:
1. Input validation (pre-conditions)
2. Core processing logic
3. Post-condition assertions for correctness verification`;
    }

    // Default conversational response
    return `I understand your request: "${userContent}".

I'm the OpenGravity Mock Provider — a fully functional development provider that requires no API keys. I can:
- Generate execution plans with structured steps
- Simulate tool calls (file read/write, commands, search, Z3 verification)
- Produce deterministic responses for testing

To use a real LLM provider, configure an API key in your .env file:
- GEMINI_API_KEY for Google Gemini
- OPENAI_API_KEY for OpenAI
- ANTHROPIC_API_KEY for Anthropic
- Or start Ollama locally for open models`;
  }

  private extractPath(text: string): string | null {
    const pathMatch = text.match(/(?:["']([^"']+)["']|(\S+\.\w+))/);
    return pathMatch ? (pathMatch[1] || pathMatch[2]) : null;
  }

  private estimateTokens(text: string): number {
    return Math.ceil(text.length / 4);
  }
}
